### ISSUE TITLE
edgemicro verify fails on verifying products availability

### ISSUE THREAD

**Issue by dmryn** [apigee-internal/microgateway#144]
Running edgemicro verify fails on verifying products availability. Not sure why this is failing because if I do a GET on {auth-uri}/products it returns a 200 OK with a list of products and info. 

I did look at the code a bit, verify.js specifically and I don't quite understand the productsUrl constant that is constructed for the verify request. 

```
// verify products endpoint availability
const productsUrl = util.format(authUri + '/products', options.org, options.env);
```

It produces the following uri which is not valid so this would always fail unless I'm missing something.
productsUrl = {auth-uri}/products myorg myenv

edgemicro verify -k redacted-key -s redacted-secret -o myorg -e myenv
current nodejs version is v8.3.0
current edgemicro version is 2.5.4
info: jwk_public_keys download from null returned 200 undefined 
info: jwt_public_key download from {auth-uri}/publicKey returned 200 OK 
info: products download from {auth-uri}/products returned 200 OK 
info: config download from {edgemicro-uri}/bootstrap/organization/myorg/environment/myenv returned 200 OK 
verifying analytics negative case: OK
verifying bootstrap url availability:OK
verifying jwt_public_key availability: OK
**verifying products availability: FAIL**
verification complete

**Comment by srinandan** [comment]
I just ran this with the latest version (v2.5.4) and works fine:
```
verifying analytics negative case: OK
verifying bootstrap url availability:OK
verifying jwt_public_key availability: OK
verifying products availability: OK
verifying quota with configured products: OK
verifying analytics with payload: OK
verification complete
```
Could it be that your edgemicro-auth proxy is not up to date?

**Comment by dmryn** [comment]
How would I verify this? I'm using version 2.5.4 which created the edgemicro-auth proxy. I even deleted the proxy and had configure recreate it again, using 2.5.4.

**Comment by srinandan** [comment]
could it be a http vs. https issue? I'm assuming there is no https.

**Comment by dmryn** [comment]
Everything in our environment is https. Our "default" vhost is secure (port 443).

**Comment by dmryn** [comment]
Also I'm now questioning the version of the "micro-gateway-products-javacallout" jar file descrepency between the core modules and this one. 

The edgemicro-auth proxy is using micro-gateway-products-javacallout-2.0.0.jar however the the edgemicro cli is using micro-gateway-products-javacallout-1.0.0.jar here https://github.com/apigee-internal/microgateway/tree/master/cli/lib

Could this make a difference? 

I still don't understand this part of code that generates an invalid http GET request URI.
// verify products endpoint availability
const productsUrl = util.format(authUri + '/products', options.org, options.env);

**Comment by srinandan** [comment]
No, the jar doesn't matter. That JAR is not used.

Can you add a debug statement and find out what the authUri is? Also start a trace session on the API proxy - see if the call even makes it there.

**Comment by dmryn** [comment]
The authUri is correct and valid as I stated in my initial post. I can also see traffic via the proxy using debug . The edgemicro gateway is working as a whole except for the verify command.

I think the problem is that verify.js is constructing an invalid http GET request as I mentioned above. The productsUri constructed contains spaces. Is that correct? I would think it might be constructed using query parms or something else to make it a valid URL or leave off the org and env altogether.

gateway:index starting edgemicro +0ms
verifying analytics negative case: OK
verifying bootstrap url availability:OK
verifying jwt_public_key availability: OK
**productsUrl="https://sandbox.api.npx.ourdomain.com/edgemicro-auth/products internal sandbox"**
verifying products availability: FAIL
verification complete

**Comment by srinandan** [comment]
aha! I know what has happened. Yes, this is a bug. The problem is the custom virtual host.

**Comment by dmryn** [comment]
Could you explain a little more? How does the virtual host play into this? The authUri is correct.

**Comment by srinandan** [comment]
Please see here: https://github.com/apigee-internal/microgateway/blob/master/cli/lib/verify.js#L115

The authUri format expect is "%s-%s.apigee.net" - for org and env. This is not the case with you. We need to fix this.

**Comment by dmryn** [comment]
Ok, but I still don't quite understand. If I'm following the correctly, authUri is picked up from the config file that is generated when running configure. I can see that authUri in that config file is correct, and validated that it works. Is there somewhere else in the code that is the bug and that's why I'm not following?

**config file value for authUri:**

```
edge_config:
  bootstrap: >-
   https://sandbox.api.npx.ourdomain.com/edgemicro/bootstrap/organization/internal/environment/sandbox
  jwt_public_key: 'https://sandbox.api.npx.ourdomain.com/edgemicro-auth/publicKey'
  managementUri: 'https://edge-api.npx.ourdomain.com'
  vaultName: microgateway
  authUri: 'https://sandbox.api.npx.ourdomain.com/edgemicro-auth'
  baseUri: 'https://sandbox.api.npx.ourdomain.com/edgemicro/%s/organization/%s/environment/%s'
  bootstrapMessage: Please copy the following property to the edge micro agent config
  keySecretMessage: The following credentials are required to start edge micro
  products: 'https://sandbox.api.npx.ourdomain.com/edgemicro-auth/products'
```

**verify.js console output of productUrl**
productsUrl="https://sandbox.api.npx.ourdomain.com/edgemicro-auth/products internal sandbox"
verifying products availability: FAIL
verification complete

As a side I did try this against an org on apigee and verify works fine. The difference I see is that org and env are not part of the proudctsUrl from what I'm seeing.

verify.js debug output
**private cloud**
productsUrl="https://sandbox.api.npx.ourdomain.com/edgemicro-auth/products myorg myenv"

**public cloud**
productsUrl="https://mrobida-test.apigee.net/edgemicro-auth/products"
