### ISSUE TITLE
Configure 2-way TLS between Apigee Edge Microgateway and Apigee Edge Cloud

### ISSUE THREAD

**Issue by ddraft1a** [apigee-internal/microgateway#150]
As discussed in a community [post](https://community.apigee.com/questions/49208/configure-2-way-tls-between-apigee-edge-microgatew.html), it would be good to have the possibility to secure the connection between the microgateway and Edge Cloud via a 2 way TLS.
This would allow only the microgateways having the expected client certificate to be able to perform the calls to Edge Cloud to retrieve the public key (https://myorg-myenv.apigee.net/edgemicro-auth/publicKey) and the list of products (https://myorg-myenv.apigee.net/edgemicro-auth/products).

**Comment by srinandan** [comment]
@ddraft1a , There are four endpoints in question here:

1.  `/products` - to retrieve a list of products name, configurations etc.
2. `/verifyApiKey` - to validate API Keys
3. `/publicKey` - to retrieve the public key in PEM format
4. `/jwkPublicKeys` - to retrieve one or more public keys in JWK format

I understand the need to secure endpoints 1 and 2 with client certificates. But not 3 and 4. Public keys are meant to be open for any client. Here are some examples: https://www.googleapis.com/oauth2/v3/certs or https://www.googleapis.com/oauth2/v1/certs from Google. I will submit a PR for 1 and 2. Target is 2.5.9-beta.

**Comment by ddraft1a** [comment]
Hi @srinandan,
You are completely right, so no problem in securing only endpoints 1 and 2.
Thanks a lot!

**Comment by srinandan** [comment]
Please try with 2.5.9-beta. Install as `npm install -g edgemicro@beta`

Enable two-way TLS for verify API Key:
```
oauth:
  allowNoAuthorization: false
  allowInvalidAuthorization: false
  verify_api_key_url: 'https://amer-demo13-test.apigee.net/edgemicro-auth/verifyApiKey'
  agentOptions:
    requestCert: true
    cert: cert.pem
    key: key.pem
    ca: ca.pem
    passphrase: password
```
Enable two-way TLS for products:
```
edge_config:
  ...
  keySecretMessage: The following credentials are required to start edge micro
  products: 'https://amer-demo13-test.apigee.net/edgemicro-auth/products'
  tlsOptions: 
    agentOptions:
      requestCert: true
      cert: cert.pem
      key: key.pem
      ca: ca.pem
      passphrase: password
```
