### ISSUE TITLE
User ID in the Docker image has been updated to 101 but runAsUser is set to 100

### ISSUE THREAD

**Issue by imesh** [apigee-internal/microgateway#285]
It seems like Apigee user id in the Docker image has been updated from 100 to 101 in the following commit:
https://github.com/apigee-internal/microgateway/commit/d7d88a85182862d4cb543b3029b137b8c9878e69

```
RUN addgroup --system --gid 101 apigee && \
    adduser -s /bin/sh -u 100 -S -G apigee apigee -h /opt/apigee	    adduser --shell /bin/bash --uid 101 --system --ingroup apigee --home /opt/apigee apigee
```

However, the Kubernetes manifest file still refers this value as 100:
https://github.com/apigee-internal/microgateway/blob/v3.1.3/kubernetes/edgemicroctl/install/kubernetes/edgemicro-sidecar-injector-configmap-release.yaml#L30

```
containers:
      - name: edge-microgateway
        image: gcr.io/apigee-microgateway/edgemicro:latest
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          runAsGroup: 101
```

As a result, ${APIGEE_ROOT}/.edgemicro/$EDGEMICRO_ORG-$EDGEMICRO_ENV-config.yaml file does not get created in the container startup.
