### ISSUE TITLE
EMG does not allow for per-proxy plugin chain

### ISSUE THREAD

**Issue by asnowfix** [apigee-internal/microgateway#94]
## Problem

Unlike Edge Cloud "policies", it is not possible to choose which chain of plugin (with their respective configurations) is associated with which API proxy under the `edgemicro_*` pattern. This is unlike Edge-Cloud, which allows to define a completely customized set of Policies, per API proxy.

This is a very severe limitation of the EMG hybrid model implementation.

## Suggestion

EMG should give the flexibility of defining a per-API proxy list of plugins & associated configuration. We propose the following schema, extending the list of active proxies [introduced in EMG 2.3.1](http://docs.apigee.com/microgateway/content/edge-microgateway-release-notes-0#release231-newfeaturesandenhancementsv231).

We suggest the following configuration structure, where the sequence of plugins is defined per API proxy, and a for each pugin, an optional per-plugin configuration override:

```yaml
  proxies:
    edgemicro_foo:
      # api-proxy specific sequence of plugins
      sequence:
        - spikearrest: true
        - quota: true
        - myplugin:
           # plugin-specific config override
           my-config-key: 123
           my-config-struct:
             foo: my-string
             foo: my-other-string
    edgemicro_bar:
      sequence:
        - spikearrest: true
        - myplugin-other: true
```
